version: '3'
services:
  app:
    image: my-python-app
    container_name: python-app
    networks:
      - my_network
    environment:
      MYSQL_HOST: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: my_database
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql-db
    networks:
      - my_network
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
    volumes:
      - db_data:/var/lib/mysql

networks:
  my_network:
    driver: bridge

volumes:
  db_data:
